services:
  - type: web
    name: defensor-ai
    env: python
    buildCommand: "pip install -r requirements.txt && python backend/train_model.py"
    startCommand: "python backend/app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
